.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "PLOG" "1" "February 2014" "" ""
.
.SH "NAME"
\fBplog\fR \-\- logfile helper function
.
.SH "SYNOPSIS"
\fBplog\fR \fINAMESPACE\fR \fIMESSAGE\fR
.
.br
\fBplog\fR [\fI\-l\fR | \fI\-e\fR] \fINAMESPACE\fR \fIMESSAGE\fR
.
.br
\fBplog\fR [\-d\fI] \fRNAMESPACE_  
.
.SH "DESCRIPTION"
Output to a logfile located in \fI$HOME/\.psyrendust\fR\|\. The \fINAMESPACE\fR argument is appended to the name of the logfile\.
.
.P
\fB\-l\fR      Append a \fIMESSAGE\fR to a logfile for a given \fINAMESPACE\fR
.
.P
\fB\-e\fR      Append a \fIMESSAGE\fR to an error logfile for a given \fINAMESPACE\fR
.
.P
\fB\-d\fR      Delete the log and error logfile for a given \fINAMESPACE\fR
.
.P
\fB\-\-help\fR  Display this help and exit
.
.SH "EXAMPLES"
\fBplog\fR \fI\-l\fR foobar "Logging foobar message"
.
.br
    Log a message to a logfile named \fIfoobar\fR (saves to \fI$HOME/\.psyrendust/log\-foobar\.log\fR)\.
.
.P
\fBplog\fR foobar "Logging foobar message"
.
.br
    You can optionally choose to pass no \fIOPTION\fR which is equivalent to \fBplog\fR \fI\-l\fR\|\.
.
.P
\fBplog\fR \fI\-e\fR foobar "Logging foobar message"
.
.br
    Log an error message to a logfile named \fIfoobar\fR (saves to _$HOME/\.psyrendust/log\-error\-foobar\.log)\.
.
.P
\fBplog\fR \fI\-d\fR foobar
.
.br
    Delete all \fIfoobar\fR logfiles (deletes \fI$HOME/\.psyrendust/log\-foobar\.log\fR and \fI$HOME/\.psyrendust/log\-error\-foobar\.log\fR)\.
.
.SH "AUTHOR"
.
.nf
Written by Larry Gordon
.
.fi
.
.SH "COPYRIGHT"
.
.nf
Copyright (C) 2013 Free Software Foundation, Inc\.  License GPLv3+: GNU GPL version 3 or later <http://gnu\.org/licenses/gpl\.html>\.  
This is free software: you are free to change and redistribute it\.  There is NO WARRANTY, to the extent permitted by law\.
.
.fi
